// Source the studio writes for you. Presets and precomps are ordinary function assets (stored,
// versioned, pinned and traced like any other), so the studio makes them by generating their
// source; and "save these params as the new defaults" is a precise edit of an asset's source.

import { parse } from 'acorn';

const ident = (k) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k));

/** A JS literal in the house style: single-quoted strings, unquoted keys, one level per line when long. */
export function literal(v, indent = '') {
  if (typeof v === 'string') return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
  if (v === null || typeof v !== 'object') return JSON.stringify(v);
  const inner = indent + '  ';
  if (Array.isArray(v)) {
    const flat = `[${v.map((x) => literal(x, inner)).join(', ')}]`;
    return flat.length < 90 && !flat.includes('\n') ? flat : `[\n${v.map((x) => `${inner}${literal(x, inner)},`).join('\n')}\n${indent}]`;
  }
  const entries = Object.entries(v).filter(([, x]) => x !== undefined);
  if (!entries.length) return '{}';
  const flat = `{ ${entries.map(([k, x]) => `${ident(k)}: ${literal(x, inner)}`).join(', ')} }`;
  return flat.length < 90 && !flat.includes('\n') ? flat : `{\n${entries.map(([k, x]) => `${inner}${ident(k)}: ${literal(x, inner)},`).join('\n')}\n${indent}}`;
}

/** The parameter declarations of a normalized schema, ready to write back as source. */
function declarations(schema, defaults = {}) {
  const out = {};
  for (const [name, def] of Object.entries(schema)) out[name] = { ...def, default: Object.hasOwn(defaults, name) ? defaults[name] : def.default };
  return out;
}

/**
 * A preset: the base asset with a chosen parameter set as its new defaults. It hands its params to
 * the base, so it draws exactly what the base draws with them, and it pins the base version.
 * @param {{ base: string, kind: string, title: string, description: string, tags: string[], duration: number | null, formats: string[], schema: any, params: any }} o
 */
export function presetSource({ base, kind, title, description, tags, duration, formats, schema, params }) {
  const lines = [
    `// A preset of ${base}: "${title}". Made in the studio from parameters chosen in the playground.`,
    `// Its parameters are ${base}'s, with these values as defaults; it draws by handing them to ${base}.`,
    'asset({',
    `  kind: ${literal(kind)},`,
    `  title: ${literal(title)},`,
    `  description: ${literal(description)},`,
    `  tags: ${literal(tags)},`,
  ];
  if (duration) lines.push(`  duration: ${duration},`);
  lines.push(`  formats: ${literal(formats)},`, `  uses: { base: ${literal(base)} },`, `  params: ${literal(declarations(schema, params), '  ')},`);
  lines.push('  render(f, p) {', "    return f.use('base', p);", '  },', '});', '');
  return lines.join('\n');
}

/**
 * A precomp: layers taken from a clip, drawn by f.layers inside the asset's box. Exposed params
 * reach the layers through { $param } bindings.
 * @param {{ title: string, description: string, tags: string[], duration: number, uses: Record<string, string>, params: any, layers: any[], from: string }} o
 */
export function precompSource({ title, description, tags, duration, uses, params, layers, from }) {
  return [
    `// A precomp: layers saved from ${from}. Generated by the studio; edit it like any asset.`,
    '// Each layer is placed like a clip item (transform, keyframes, motions, effects…) inside this',
    "// asset's box; a param value { $param: 'name' } is filled from this asset's own params.",
    `const LAYERS = ${literal(layers)};`,
    '',
    'asset({',
    "  kind: 'visual',",
    `  title: ${literal(title)},`,
    `  description: ${literal(description)},`,
    `  tags: ${literal(tags)},`,
    `  duration: ${duration},`,
    `  uses: ${literal(uses, '  ')},`,
    `  params: ${literal(params, '  ')},`,
    '  render(f, p) {',
    '    f.layers(LAYERS, p);',
    '  },',
    '});',
    '',
  ].join('\n');
}

/**
 * The same source with new defaults for some parameters: each `default:` in the params declaration
 * is replaced (or added) in place; nothing else in the file changes.
 * Throws when the source does not declare them in a way that can be edited safely.
 */
export function rewriteDefaults(source, values) {
  let ast;
  try { ast = parse(source, { ecmaVersion: 'latest', sourceType: 'script', ranges: true }); } catch (e) { throw new Error(`the source does not parse: ${e.message}`, { cause: e }); }
  let call = null;
  const walk = (node) => {
    if (!node || typeof node !== 'object' || call) return;
    if (node.type === 'CallExpression' && node.callee.type === 'Identifier' && node.callee.name === 'asset' && node.arguments[0]?.type === 'ObjectExpression') { call = node; return; }
    for (const v of Object.values(node)) {
      if (Array.isArray(v)) v.forEach(walk);
      else if (v && typeof v.type === 'string') walk(v);
    }
  };
  walk(ast);
  if (!call) throw new Error('no asset({...}) call with an object literal');
  const keyOf = (p) => (p.type === 'Property' && !p.computed ? (p.key.type === 'Identifier' ? p.key.name : p.key.value) : null);
  const paramsProp = call.arguments[0].properties.find((p) => keyOf(p) === 'params');
  if (!paramsProp || paramsProp.value.type !== 'ObjectExpression') throw new Error('params is not declared as an object literal in asset({...})');
  const edits = [];
  for (const [name, value] of Object.entries(values)) {
    const decl = paramsProp.value.properties.find((p) => keyOf(p) === name);
    if (!decl) throw new Error(`parameter "${name}" is not declared in params`);
    if (decl.value.type !== 'ObjectExpression') throw new Error(`parameter "${name}" is not declared as an object literal`);
    const def = decl.value.properties.find((p) => keyOf(p) === 'default');
    if (def) edits.push({ from: def.value.range[0], to: def.value.range[1], text: literal(value) });
    else {
      const props = decl.value.properties;
      const at = props.length ? props[props.length - 1].range[1] : decl.value.range[0] + 1;
      edits.push({ from: at, to: at, text: `${props.length ? ', ' : ' '}default: ${literal(value)}${props.length ? '' : ' '}` });
    }
  }
  let out = source;
  for (const e of edits.sort((a, b) => b.from - a.from)) out = out.slice(0, e.from) + e.text + out.slice(e.to);
  return out;
}
